### ISSUE TITLE
OutlineInputBorder (In general InputBorders)

### ISSUE THREAD

**Issue by seel-channel** [howshea/smooth_corner#1]
Hello bro! Your package saved me a lot of work, your ClippRRect and ShapeBorder are working super fine (super smooth without weird effects)!  

Can you add OutlineInputBorder? It doesn't a big problem. I cannot see a big difference on Inputs because are pretty small (48px) compared to my cards (150px)

See you!

**Comment by migalv-fu** [comment]
Yeah I need this for my app

**Comment by howshea** [comment]
The SmoothOutlineInputBorder has been implemented in the feature/smoothInputBorder branch. However, it has not been released in the official version yet, as it doesn't fully support labelText at present.
