### ISSUE TITLE
Error in latest version flutter 3.27.1

### ISSUE THREAD

**Issue by karthikeyan9952** [howshea/smooth_corner#3]
/C:/Users/Karthikeyan/AppData/Local/Pub/Cache/hosted/pub.dev/smooth_corner-1.1.0/lib/src/smooth_rectangle_border.dart:226:12: Error: The method 'hashValues' isn't defined for the class 'SmoothRectangleBorder'.
 - 'SmoothRectangleBorder' is from 'package:smooth_corner/src/smooth_rectangle_border.dart' ('/C:/Users/Karthikeyan/AppData/Local/Pub/Cache/hosted/pub.dev/smooth_corner-1.1.0/lib/src/smooth_rectangle_border.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
    return hashValues(
           ^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 30s
Running Gradle task 'assembleDebug'...                             31.0s
Error: Gradle task assembleDebug failed with exit code 1

Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.96.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by MoinHashmi** [comment]
I am having same issue

**Comment by karthikeyan9952** [comment]
# Here is the solution
## Step 1:
Download the source code from this repository
## Step 2:
Unzip and rename the folder smooth_corner-main to smooth_corner
## Step 3:
Move the folder into the "packages" folder in your project root directory
## Step 4:
```yaml
dependencies:
smooth_corner:
    path: packages/smooth_corner
```
